name: testmaker
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.6.1 <4.0.0"
description: A new Flutter project.
dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.5
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  very_good_analysis: ^7.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/quizzes/sample_quiz.json
