name: testmaker
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.6.1 <4.0.0"
description: A new Flutter project.
dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.5
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  shared_preferences: ^2.3.3
  syncfusion_flutter_pdfviewer: ^28.2.8
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  very_good_analysis: ^7.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/quizzes/sample_quiz.json
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo/app_logo.png
  min_sdk_android: 21
  remove_alpha_ios: true
